# Generated by Django 5.2.7 on 2025-11-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('resource_link', models.URLField(blank=True)),
                ('lecturer_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
