# Generated by Django 5.2.7 on 2025-11-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lecturer_email',
        ),
    ]
