# Generated by Django 5.2.6 on 2025-11-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0002_remove_course_lecturer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
